name: FXServer version checker
# on:
#   schedule:
#     - cron:  '*/30 * * * *'
on: push
jobs:
  fivem-checker:
    runs-on: ubuntu-latest
    steps:
      - id: latest-fivem-tag
        run: |
          echo ::set-output name=tag::$(curl -fH "Accept: application/vnd.github.v3+json" --url "https://api.github.com/repos/citizenfx/fivem/tags?per_page=100" | jq -r 'first(.[] | {name: .name | match("v1.0.0.(\\d+)").captures | .[].string}).name')
      - id: docker-image
        uses: javajawa/check-registry-for-image@v1
        with:
          registry: hub.docker.com
          repository: traskin/fxserver
          tag: ${{ steps.latest-fivem-tag.outputs.tag }}
          auth: '{"Username": ${{ secrets.DOCKERHUB_USERNAME }}, "Secret": ${{ secrets.DOCKERHUB_SECRET }}}'
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        if: ${{ steps.latest-fivem-tag.outputs.tag != null }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        if: ${{ steps.docker-image.outputs.exists == 'false' }}
        with:
          push: true
          build-args: |
            artifact=${{ steps.latest-fivem-tag.outputs.tag }}
          tags: |
            traskin/fxserver:${{ steps.latest-fivem-tag.outputs.tag }}
            traskin/fxserver:latest
