name: Set release tags
on:
  workflow_dispatch:
    inputs:
      fxserver_version:
        required: true
        type: number
      tag:
        required: true
        type: choice
        default: "all"
        options:
          - recommended
          - optional

jobs:
  release-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker pull
        run: |
          docker pull traskin/fxserver:${{ inputs.fxserver_version }}
      - name: Add tag to the image
        run: |
          docker tag traskin/fxserver:${{ inputs.fxserver_version }} traskin/fxserver:${{ inputs.tag }}
      - name: Push tagged image
        run: |
          docker image push traskin/fxserver:${{ inputs.tag }}
